
---
title: "Creating a blog"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    
    latex_engine: xelatex
  tufte::tufte_book:
    
    latex_engine: xelatex
---


# using a blog


## Why?

One thing that i learned from last semester is that the discussion boards didn't seem to work very well. They are somewhat old school anyway and don't really emmulate how modern disucssions go. plus, the idea that you need to do X number of posts and Y number of responses just seems to produce quantity rather than quality.

Instead, we are going to try something different. Each of you will make a blog and use that to post notes, thoughts, reflections, etc (feel free to make it anonymous). My hope is that you will use this blog to not only respond to questions, but to reflect about class themes and ideas. I hope it would allow for a more critical, problem-posing learning. 


While we are doing this in the open, i know that some might not want to have their name attached. THe 4th link here talks about how to be anonymous. If you would rather do that, that is totally fine. I'll have to know which blog is yours but I'll delete all info i have after class ends. You could even setup a seperate email account when you log into Blogger if you prefer (that is what i did when i had a blog in grad school that i have since forgoteen how to log into..)

## *steps to create a blog* from Laura Gibbs 

- [Starting a Blog: Your First Post](http://oudigitools.blogspot.com/2020/05/starting-blog-your-first-post.html)
- [Blog URLs: Homepage and Posts](https://oudigitools.blogspot.com/2020/05/blog-urls-homepage-and-posts.html)
- [Online Identity and Pseudonyms](https://oudigitools.blogspot.com/2020/05/online-identity-and-pseudonyms.html)
- [Configuring Your Blog for Comments](https://oudigitools.blogspot.com/2020/05/configuring-your-blog-for-comments.html)
- [Other Basic Blog Settings](https://oudigitools.blogspot.com/2020/05/other-basic-blog-settings.html)


## posts

In the course calendar you will find the times that i ask you to respond to writings and ideas. But you don't have to only post then. Use the blog however you see fit. If one of the posts doesnt seem useful to you just let me know. I want these posts to not seem like busy work


# lists of blog posts

- post on decolonizing human origins[ [info posted on day 2](https://marckissel.github.io/Anthro_4320/calendar.html#wednesday-may-27---decolonizing-human-evolution-day-2) ] (aim by Friday May 29 at 11:59 PM)
- post on If humans came from chimps, why are there still chimps? [ [info posted on day 4](https://marckissel.github.io/Anthro_4320/calendar.html#monday-june-1---primates-day-4) ] (aim for Friday June 5th at 11:59 PM)
- post on skeletal evidence of bipedalims [ [info posted on day 6](https://marckissel.github.io/Anthro_4320/calendar.html#wednesday-june-3---the-first-hominins-day-6) ] (aim for  Monday June 8 at 11:59 PM)
- post on Ardipithecus[ [info posted on day 8](https://marckissel.github.io/Anthro_4320/calendar.html#monday-june-8---ardipithecus-day-8) ]  (aim for  Friday June 12th at 11:59 PM)
- post on "when two hominins meet" [ [info posted on day 13](https://marckissel.github.io/Anthro_4320/calendar.html#tuesday-june-16---homo-erectus-day-13) ]  (aim for Monday, June 22 by 11:59 PM)
- last post on "why this all matters" [ [info posted on day 15](https://marckissel.github.io/Anthro_4320/calendar.html#thursday-june-18---the-first-homo-sapiens-day-15) ] (aim for  Wendesday June 24th at 11:59 PM)


# comments

As you can [read here](https://oudigitools.blogspot.com/2020/05/configuring-your-blog-for-comments.html), it is pretty easy to configure your blog for comments. Once you have all set up a blog I will post links on my blog (the main site for this class!) and as a list I will share. You can also use Slack to let us know when you have a new post!

You should check often to see if there are any new blog posts by your fellow classmates (One way to do this is to use [Inoreader](https://www.inoreader.com) to set up a feed. For help on this [see here](https://oudigitools.blogspot.com/2020/05/what-is-rss-and-what-is-inoreader.html).

There is no 'set number of comments' that you must make. But I hope that you interact and leave comments when you feel motivated to do so



