
---
title: "Online game"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    
    latex_engine: xelatex
  tufte::tufte_book:
    
    latex_engine: xelatex
---

# Making an interactive game

The major group project for this course is to create a location-based  game. We are going to use [Aris](https://fielddaylab.org/make/aris/) to make a situated documentary game that teaches the player about the fossil record of human evolution. Everyone will choose a fossil/skeleton and research information on that. This info will be used to both create an interactive presentation using [Sutori](https://www.sutori.com/) and then used as part of the game info.

Aris lets players interact with real world locations. Since we can't walk around and visit these sites, we can use this to get a feel for where sites are located and what sorts of information we can learn. The software is a bit wonky but i think it would be more interesting/fun than writing a paper!


# Basic idea

[Here is a video that shows how students have used Aris to learn](https://www.youtube.com/watch?v=tt6rn5fVnN4&feature=emb_logo)


Now, follow along below to learn to create an account and make a game:

[video tutorial](https://fielddaylab.wisc.edu/courses/aris)

[and the manual](https://manual.arisgames.org/)



[more info](https://casls.uoregon.edu/wp-content/uploads/sites/7/2018/07/ARIS_in_the_classroom.pdf)


# Our game

Obviously we can't go to these places, but the game itself lets you pretend to visit. So, what i want to do is make a marker for the location the fossil comes from and then use that as a way to let players learn more about the site, fossil, etc. We could have players interact with the person who found or studied the fossil and have them ask questions. They can also 'get' the fossil to carry around and maybe bring it to a lab to study.
I haven't used this before so it might not work 100% but should be interesting to play around with even if it 'fails'


## Optional: install software on your phone

If you have a smart phone try to install the software (note: if you are like me and have an Android it is a bit harder. see if you can follow this but otherwise I'll work on giving a more detailed instruction. https://fielddaylab.wisc.edu/forums/viewtopic.php?f=13&t=169)


# calendar


## week 1 - setup and learn how to use it though tutorial. 

at end of week I'll do a quick checkin and see what y'all think

## week 2 - plan out and do rearch on your fossil. 

use this time to research background on the site and fossil. things to think about
- location
-age
-species
-ssssss

start  planning out the interactions etc you want to happen at the site

## week 3- start to build it using the group Aris project (will get an invite!)

- this will be a bit harder since the software isn't that easy to use. give yourself time and remember that it might take some practice. you should 


## week 4- test and comment on other aspects

- now, look at others. if you can lay the app on your phone do that and see what happens. if you cant and can't borrow someones phone then just click around and see what needs to be fixed. 
we can advice into teams (testers and fixers). test test out the software and fixers see about fixing thing like spelling issues etc. We will use our Slack to do this

