
# class projects

## your blog

## our game

## assessments

## timeline?

## capstone?


# Course Calendar

dates: 05/26-06/26

## Tuesday, May 26 (day 1)

Today we are going to get things setup for our online class!


### create an account on Perusall (make sure to use the class code KISSEL-6N6B8 when you sign up so you get access to our site ) 

- all the class articles are there. You don't have to comment  on all of them but i ask that you do so a few times during the week at least. You can also answer or respond to other comments. This is sort of taking the place of the standard disucssion board which seems to never work very well 
- to demo Perusall, look at the first paper listed "on Love and other data." make at least one annoatin/response

### Join the class Slack

post a hello message. I'll be on Slack all day to help folks set things up

### Create a blog (see steps here!)

note: While we are doing this in the open, i know that some might not want to have their name attached. THe 4th link here talks about how to be anonymous. If you would rather do that, that is totally fine. I'll have to know which blog is yours but I'll delete all info i have after class ends. You could even setup a seperate email account when you log into Blogger if you prefer (that is what i did when i had a blog in grad school that i have since forgoteen how to log into..)

*steps to create a blog* from Laura Gibbs 

- [Starting a Blog: Your First Post](http://oudigitools.blogspot.com/2020/05/starting-blog-your-first-post.html)
- [Blog URLs: Homepage and Posts](https://oudigitools.blogspot.com/2020/05/blog-urls-homepage-and-posts.html)
- [Online Identity and Pseudonyms](https://oudigitools.blogspot.com/2020/05/online-identity-and-pseudonyms.html)
- [Configuring Your Blog for Comments](https://oudigitools.blogspot.com/2020/05/configuring-your-blog-for-comments.html)
- [Other Basic Blog Settings](https://oudigitools.blogspot.com/2020/05/other-basic-blog-settings.html)



### when you have created your blog send me a link!




## Wednesday, May 27 - Decolonizing Human Evolution (day 2)

**Read the following articles:**

- Athreya and Ackermann 2018 Colonialism Narratives Human Origins Asia Africa
- Dunsworth_2018_It is unethical to teach evolution without confronting racism and sexism 
- ADD BLACK FEMINISM


**Now, Here's what i want you to do:**

1. Write your first blog post based on the readings. One topic could be how your previous classes have dealt w/ the issues raised in the readings, examples of how this can be done better, or simply what you thought while reading the two papers. 

2. Follow the directions below to start with Aris...

***Please have this posted by Friday May 29 at 5:00 pm if possible***


**Here's why I Want you to do it:**

We want to begin to think about who gets to tell the story of human origins. As we all know, there is a lot of controversy about where we come from. But rather than center a debate about creationism (though you are free to explore that in your post!) I thought it would be interesting to see how recent work is pushing against the narrative in a different way 



**Here's how to do it:**

- Use the 3 papers (and any others you know of/can find) as a scaffold for the post. You don't have to reference them all and there is no set format for referencing
- Think about [adding visuals to your blog](https://oudigitools.blogspot.com/2020/05/images-in-posts.html)
- make sure to add the tag #Ant4320 so we can find it!








## Thursday, May 28 - Evo theory (day 3)

**Read the following articles:**

- Gould and Lewontin 1979 The Spandrels of San Marco and the Panglossian Paradigm-A Critique of the Adaptationist Programme
- [The selfish gene is a great meme. Too bad it’s so wrong](https://aeon.co/essays/the-selfish-gene-is-a-great-meme-too-bad-it-s-so-wrong)


**Now**

- make annotations on these two articles. you could ask for clairifaiton on these ides or just explore your thoughts

- Optional Zoom meeting: 

 If you can make it we will be up on Zoom to talk about the articles for this week at around 1 PM - 2 PM. 




## Monday, June 1 - What is a primate? (day 4)
**Read the following article:**

[Plavcan 2001 Sexual Dimorphism in Primate Evolution]()


**Now**, 


 Write your  blog post based on the questions "if humans came from chimps, why are there stil chimps"




## Tuesday, June 2 - (day 5)

**Read the following articles:**

Ko 2015-origins of bipdealism
Lovejoy 1981-The origin of man 


**Now**, 

make comments on Persual on these papers. no set number of comments. and over the day check and respond to other


write a blog post on how sexual dimoprhism might be relevant to paleoanthropolgoy. Think abouthow we can infer sexual dimporhism in the past and what it might mean if we see a speices with hihg levles or low levels of sd. Please have this posted by Thursday June 4 at 5:00 pm if possible  


## Wednesday, June 3 (day 6)

**Read the following article:**

Brunet et al - A new hominid from the Upper Miocene of Chad, Central Africa
Pickford et al - Bipedalism in Orrorin tugenensis revealed by its femora


**Now**, 

write up a short post on your blog that examines one aspscte of early hominin bipedalism. you could use the readings for today and yesterday or you could pick something else. SOme questions you might want to look at include:
- what does the current data suggest about eatly biedlaism
- wht do we know about bipdealism in other nonhuman primates

Please have this posted by Monay June 8 at 5:00 pm if possible 

## Thursday, June 4 (day 7)

**Read the following article:**

Watch this documentary on 


we are gping to watch these:

[Early Hominin Body Form](https://carta.anthropogeny.org/mediaplayer/play/5367/3264)
[The Evolution and Relevance of Human Running](https://carta.anthropogeny.org/mediaplayer/play/5371/3272)
[The Parallel Evolution of Humanity and Savagery](https://carta.anthropogeny.org/mediaplayer/play/20547/7939)

we can jump on Slack to watch together at XXXX or watch them by yourself and comment on slack afterwards

**Now**, 


## weekend works




## Monday, June  8 (day 8)

**Read the following articles:**

White et al. 2009
Lovejoy 2009


**Now**, 

Pick one of the articles below and read it in depth. prepare a blog post for Wed June 10th on it



## Tuesday, June 9 (day 9)

**Read the following article:**

https://www.sciencenews.org/article/australopithecus-anamensis-skull-reveals-face-lucy-possible-ancestors
Halie-Selassie et al 
White et al 2006


**Now**, 
work on Aris project (draft what you are going to do etc. use the sign up sheet to pick a fossil)

- Optional Zoom meeting: 

 If you can make it we will be up on Zoom to talk about the articles we have read from 1 PM - 2 PM. 




## Wednesday, June 10 (day 10) Australopiths continued

**Read the following article:**
**Now**, 

## Thursday, June 11 (day 11) early Homo

**Read the following article:**

new stuff 
**Now**, 
slack checkin




Make a site with Sutori.....this site should be based on the fossil you are using for Aris. This way we cna hve it to link to.

## Monday, June 15 (day 12)

**Read the following article:** early homo, part 2
add all the new early homo stuff from last few weeks
**Now**,

## Tuesday, June 16 (day 13) break from reading

**Read the following article:**
**Now**, 

blog

## Wednesay, June 17 (day 14) Homo erectus

**Read the following article:**
**Now**, 

## Thursday, June 18 (day 15) Middle Plies
**Read the following article:**
**Now**, 


## Monday, June 22 (day 16) Neandertals

**Read the following article:**
**Now**,

## Tuesday, June 23 (day 17) Homo naledi doc

**Read the following article:**


**Now**, 

jump on and watch this


## Wednesay, June 24 (day 18): MHO

**Read the following article:**
**Now**, 

## Thursday, June 25 (day 19) Future

**Read the following article:**
**Now**, 


## Friday, June 26 (day 20)

Last day!




# to add

https://theconversation.com/prehistoric-human-footprints-reveal-a-rare-snapshot-of-ancient-human-group-behavior-138502

# Projects


getting Aris ready

- Online game:

https://fielddaylab.org/make/aris/


check out the website above and play around with it. Setup an accont and, use the [manual to make a tutorial game](https://manual.arisgames.org/home).

If you have a smart phone try to install the software (note: if you are like me and have an Android it is a bit harder. see if you can follow this but otherwise i'll work on giving a more detailed instrution. https://fielddaylab.wisc.edu/forums/viewtopic.php?f=13&t=169)


other useful links:

https://casls.uoregon.edu/wp-content/uploads/sites/7/2018/07/ARIS_in_the_classroom.pdf


ONce we plan out we will start to build it. I'll nvite everyone to join my setup one(unless someoen wants to take chage). then in teasm you will build the part you asked to do

More: we will work on this game in Slack etc. 

- week 1 - setup and learn
- week 2 - plan out and do rearch in groups for the diffeent fossils
- week 3- start to build it
- week 4- test and add




```{marginfigure, echo= TRUE}

Please see the course handouts for details on these projects
```
## Reading response

For each course reading answer the questions provided.
```{marginfigure, echo= TRUE}

You can find the questions for each article [here](https://marckissel.github.io/2020_Spring_Bioanth/course_reading_questions/Questions.html)
```

We will collect them at the end of the class and provide feedback. 

## Labs & group work

Working hands-on with course material to  build information, labs, infographics, etc to learn about BioAnth

## Quizzes

A handful of in-class quizzes used to assess learning 

## Essay responses

4 essay questions throughout the semester. Will be shared for peer-comments. Then pick one and resubmit based on comments



## UnEssay

You choose your own topic and present it how you please (written word, illustrations, music, video, etc.)


## Personal Assessment

Done 3 times during the semester. Will use self-guided form to see how you feel about your work in the class

# Final assessment

`r newthought('This course is about qualitative')` rather than quantitative assessment. In other words, we focus on learning rather than memorizing. You will get feedback (from both me and fellow students) throughout the semester but I won’t be putting a grade on any assignments. At the end of the class we will meet to talk about what you got out of the class. 

You will be collaborating with peers on many of the assignments for this course. If you have questions about the various ways collaboration can work, feel free to chat with me at any point.



## But what is my grade?
who are trained to memorize facts, hold back what we really think, and avoid taking risks for fear that it will hurt our grade. Learning has been replaced by the ideas of 'achievement.' We thus value grades over true, real learning. This class is an experiment in actual learning. There are no tests planned.
`r newthought('Sadly, most of us')` have been conditioned to be worker-learners 
```{marginfigure, echo= TRUE}

Based on student feedback we will have in-class quizzes that you can use to help assess your own learning. You can use these to help guide your work in the class
```
Rather I strive to avoid busy work and turn the classroom into a place of active learning, whether though lecturing, discussing, or reading. However, this does not mean there is no work. 

`r newthought('At the end of the semester')`, you will tell me what grade you think you deserve in the class. You can use the labs, quizzes, reading prompts, and essays to help you assess your own learning. However, I reserve the right to be the final arbiter of your grade. 

If at any time you are concerned about your progress please let me know and we will set up a time to talk.












.




.

